### ISSUE TITLE
Repo contains binary result files 

### ISSUE THREAD

**Issue by dietmarw** [droberg/Modelica-MVEM#3]
Any particular reason why you would want to put the generated binary mat files under version control? I can't see any of the models using them so they should be excluded from the repo.

**Comment by droberg** [comment]
Hi, these are Dymola result files and they are there for debug reasons. 

At the time of development of the library not many tools could handle the library and one common way to make sure that the results are valid is to check against Dymolas results because they are  often correct.  

Not everyone has Dymola and I myself does not always have access to a valid licensed copy.

**Comment by dietmarw** [comment]
OK that explains it. :-)
